apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pnb47h792-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pnb47h792-nodejs 
  name: pnb47h792-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pnb47h792-nodejs 
